version: '2.2'
services:
    simpleservice-app:
        build:
              context: target
              dockerfile: Dockerfile
        image: simple-service
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10
        ports:
            - 443:8443
            - 10000:10000
