version: '2'
services:
    simpleservice-app:
        build:
              context: target
              dockerfile: Dockerfile
        image: simple-service
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
        volumes:
            - /Users/Jerry/Documents/files/images:/images
        ports:
            - 8443:8443
