version: '2'
services:
    simpleservice-app:
        image: simpleservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8443:8443
            - 10000:10000
